### ISSUE TITLE
build success on Fedora Linux

### ISSUE THREAD

**Issue by davephillips** [knchaffin/Meander#3]
Fedora 23 Linux
VCV Rack v1.dev
GCC 5.3.1

Greetings ! I just wanted to let you know that I've successfully compiled your plugin, tests so far indicate that it's working. I assume that some parts are unfinished ? 

Running here at Studio D:

![meander-test-1-cabled](https://user-images.githubusercontent.com/7815938/70400234-dcc90700-19f7-11ea-8146-6d8865aa747a.png)

So far, so good. I'll keep following development and will report here. Thanks for the cool plugin !

**Comment by knchaffin** [comment]
Hi Dave.  Glad to hear Meander built and is running.  Yes, I am still developing and not all functionality is in place.  Several of the developers encouraged me to do the public release so that we could get an early look at any issues related to builds on Linux and MacOS.  I also feel better that there were just a couple of issues to resolve to run on Linux.

 

Ken
